### PR TITLE
Added spec file for nested component with injected parent use case

### PR DESCRIPTION
**Pull request by manojvignesh**
I can do a full code clean up if needed. I'm seeing so many ts-lint errors

### CODE REVIEW

**Comment by juristr** [comment]
@manojvignesh Hey, thanks a lot for your contribution. Going to give it a look these days and merge it in. Thanks a lot 👏

**Comment by manojvignesh** [comment]
My first Pull Request :heart_eyes:

**Comment by juristr** [comment]
Yes I've seen, let's make this happen 😄 👊 . Today evening after work I have some time to look at this.

**Comment by juristr** [comment]
Ok, merged it in 🎉 👍 .

Just changed the commit message to match the [conventional commit messages](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#commits) which I'm adopting here. The rest is fine, thanks 😃.

A thing I'm currently thinking about is how to organise these tests in a better way. Because for instance in your test you're actually testing Angular itself in some way, right. Like whether the injection of a parent component actually works. I did that as well in a couple of tests, and totally on purpose because it's useful for someone in the sense that he sees how he has to setup the test scenario and adapt it to a more real use case one might encounter in an app.
Still I'm thinking to maybe change some of the tests to be "more real life"...but just ignore this paragraph. It's just me thinking aloud here haha 😄 .

Again thanks for your 1st PR :1st_place_medal:

**Comment by manojvignesh** [comment]
@juristr Thanks for merging my first PR :heart_eyes: 
> Just changed the commit message to match the conventional commit messages which I'm adopting here. 

I don't know that there is a conventional commit message format but i'll follow from now on. Thanks for letting me know. May be you can add Contributing.md file.
> Because for instance in your test you're actually testing Angular itself in some way, right.

It never thought that test as testing angular itself but after you mentioned i can agree with you.
> A thing I'm currently thinking about is how to organize these tests in a better way.
Still I'm thinking to maybe change some of the tests to be "more real life"

Just make me understand what you've in your mind. I'll contribute.

**Comment by juristr** [comment]
Hey,

> I don't know that there is a conventional commit message format but i'll follow from now on. 

Well it's not something that everyone follows, but many do (i.e. the Angular repository). Yes, I should maybe add it in the contributing file. I'll copy it over from another repo where I have it there already. Thx for that hint.

> Just make me understand what you've in your mind. I'll contribute.

Good to know. I'll let you know, still have to think about it 😄

**Pull request merged**
